name: sol005-lifecycle-driver
version: 0.1.2
apiVersion: v1
description: A Helm chart for the SOL005 NFVO Driver
maintainers:
  - name: Accanto Systems
    email: containers@accantosystems.com
icon: # http://www.accantosystems.com/wp-content/uploads/2017/06/Accanto-w_white-systems200px.png
keywords:
- LM
- ALM
- SLM
- Lifecycle
- IBM
- ETSI
- SOL005
- NFVO
- Driver
engine: gotpl
